version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
  build:
    commands:
      - echo "Zipping and Deploying Lambda Functions..."
      # 1. Pehle files ko zip karo
      - zip -j extractor.zip src/taxi_extractor_lambda.py
      - zip -j transformer.zip src/taxi_transformer_lambda.py
      - zip -j loader.zip src/taxi_loader_lambda.py
      # 2. Ab real zip files deploy karo
      - aws lambda update-function-code --function-name taxi-extractor-service --zip-file fileb://extractor.zip
      - aws lambda update-function-code --function-name taxi-transformer-service --zip-file fileb://transformer.zip
      - aws lambda update-function-code --function-name taxi-loader-service --zip-file fileb://loader.zip
artifacts:
  files:
    - '**/*'