name: CI CD Data Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # 1. AWS Credentials configure karna (jo secrets humne save kiye hain)
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    # 2. Files ko alag-alag zip karna AWS ke liye
    - name: Zip Lambda Functions
      run: |
        cd src
        zip ../extractor.zip taxi_extractor_lambda.py
        zip ../transformer.zip taxi_transformer_lambda.py
        zip ../loader.zip taxi_loader_lambda.py
        cd ..

    # 3. AWS Lambda functions ko update karna
    - name: Deploy to AWS Lambda
      run: |
        aws lambda update-function-code --function-name taxi-extractor-service --zip-file fileb://extractor.zip
        aws lambda update-function-code --function-name taxi-transformer-service --zip-file fileb://transformer.zip
        aws lambda update-function-code --function-name taxi-loader-service --zip-file fileb://loader.zip