name: CI CD Data Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Zip Lambda Functions
      run: |
        zip -j taxi_extractor_lambda.zip src/taxi_extractor_lambda.py
        zip -j taxi_transformer_lambda.zip src/taxi_transformer_lambda.py
        zip -j taxi_loader_lambda.zip src/taxi_loader_lambda.py

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: lambda-packages
        path: |
          taxi_extractor_lambda.zip
          taxi_transformer_lambda.zip
          taxi_loader_lambda.zip